# Generated by Django 4.1.2 on 2023-01-30 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add new feature', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('number', models.SmallIntegerField()),
                ('birudingu', models.SmallIntegerField(default=-1)),
                ('street', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, help_text='fee charged per hour', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('discounts', models.TextField(blank=True, null=True)),
                ('alcoholRules', models.CharField(blank=True, choices=[('f', 'Forbidden'), ('a', 'Allowed'), ('a', 'Forbidden with your own')], default='f', help_text='alcohol restrictions', max_length=1)),
                ('smokingRules', models.CharField(blank=True, choices=[('f', 'Forbidden'), ('a', 'Allowed'), ('r', 'Special room')], default='f', help_text='smoking restrictions', max_length=1)),
                ('ageRules', models.CharField(blank=True, choices=[('e', 'Everyone allowed'), ('f', '18+')], default='e', help_text='age restrictions', max_length=1)),
                ('feature', models.ManyToManyField(help_text='Add location of the place', to='places.feature')),
                ('location', models.ManyToManyField(help_text='Add location of the place', to='places.location')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add new place type', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(help_text='Enter location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.location')),
                ('network', models.ForeignKey(help_text='Enter network', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.network')),
            ],
        ),
        migrations.AddField(
            model_name='network',
            name='type',
            field=models.ManyToManyField(help_text='Add type of the place (e.g. anti-cafe or coworking)', to='places.type'),
        ),
    ]
